# Constants
LINK_WIDTH = 3.5
LINK_LENGTH = 100
VEHICLE_SPEED = 49.02
SLOT_SPEED = 50
CONFLICT_AREA_START_HORIZONTAL = (LINK_LENGTH - LINK_WIDTH) / 2
CONFLICT_AREA_END_HORIZONTAL = (LINK_LENGTH + LINK_WIDTH) / 2
CONFLICT_AREA_START_VERTICAL = (LINK_LENGTH - LINK_WIDTH) / 2
CONFLICT_AREA_END_VERTICAL = (LINK_LENGTH + LINK_WIDTH) / 2

LOG_FILE_BASE_NAME = 'logs_000.txt'
LOG_FILE_DIR = 'logs/'